### ISSUE TITLE
Store property IDs and other info in Redis

### ISSUE THREAD

**Issue by O1sims** [O1sims/Sukasa#12]
## Problem
Instead of hitting the DB all the time when checking for existing properties, let's store of the property IDs in a Redis DB so that we can just check items in memory.

## Solution
Need to create a new Docker container that hosts an instance of Redis and exposes the relevant ports. Something like this:
```
redis:
  container_name: redis
  restart: unless-stopped
  image: redis:latest
  ports:
    - "6379:6379"
```
And make the main Sukasa application depend on this Redis container.

This issue will be carried out on the `enhancement-redis` branch.
